services:
  postgres:
    image: postgres:16
    container_name: postgres_db2
    restart: always
    environment:
      POSTGRES_USER: cibi
      POSTGRES_PASSWORD: 599663
      POSTGRES_DB: quickpoll
    ports:
      - "5433:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data

volumes:
  postgres_data2:
